### ISSUE TITLE
Cozy Homes: Kanban Board Frontend

### ISSUE THREAD

**Issue by HunterX-7** [HunterX-7/cozy-homes-front-end#10]
## Dear code reviewer this is a Kanban Board set up for the Frontend:

We are a group of 5:

- @HunterX-7 
- @cilfonegabriel 
- @MarcoAurelioAntonio 
- @Juanpa8830 
- @PierreBarba 

This is the link to our [Kanban board](https://github.com/users/HunterX-7/projects/2/views/1).

![Capturafront](https://github.com/HunterX-7/cozy-homes-front-end/assets/90111138/89543757-c60a-4d70-b367-0d69d0c229ab)

**The Backend issue is [here](https://github.com/HunterX-7/cozy-homes-back-end/issues/10).**

## I Hope you have a great day and your support is much appreciated! 😄

**Comment by Meltrust** [comment]
Hi @HunterX-7,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have been pointed, assigned, and have descriptions ✔️
- The cards cover the project reqs ✔️ 
- The pointings are fair according to the requirements ✔️  


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
